spring:
  application:
    name:
      c2b-ai-agent
  profiles:
    active: local
server:
  port: 8123
  servlet:
    context-path: /api
# springdoc-openapi项目配置
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /v3/api-docs
  group-configs:
    - group: 'default'
      paths-to-match: '/**'
      packages-to-scan: com.c2b.c2baiagent.controller
# knife4j的增强配置，不需要增强可以不配
knife4j:
  enable: true
  setting:
    language: zh_cn
#logging:
#  level:
#    # 开启 Spring AI 的日志
#    org.springframework.ai: DEBUG
#    # 开启 HTTP 客户端日志（如果是用的 RestTemplate 或 WebClient）
#    org.springframework.web.client: DEBUG
#    # 如果你使用了 OkHttp 或其他底层 HTTP 客户端，也需要开启